# to create docker images

gfan:
	sudo docker build -f gfan/Dockerfile -t mikestillman/gfan .

basicreveng:
	sudo docker build -f basicRevEng/Dockerfile -t mikestillman/basicreveng .

run-gfan:
	sudo docker run -t -i mikestillman/gfan /bin/bash

run-basicreveng:
	sudo docker run -t -i mikestillman/basicreveng /bin/bash
