FROM ahosny/algorun

MAINTAINER Your Name <your_email@domain.com>

# Add your algorithm code foler to /home/algorithm/src/
# EXAMPLE: ADD ./src /home/algorithm/src/

# Add any algorithm dependencies here
# EXAMPLE: RUN apt-get -y wget

# Add your command to execute an algorithm as environment variable EXEC_COMMAND
# EXAMPLE: ENV EXEC_COMMAND "ruby test.rb"

# Add your command options (if any) as environment variable COMMAND_OPTIONS
# EXAMPLE: ENV COMMAND_OPTIONS "-c"

# If you specified -f as a command line option for the output file, ignore this step
# If your code outputs results to a hard-coded file name, specify it as environment variable OUTPUT_FILE_NAME
# EXAMPLE: ENV OUTPUT_FILE_NAME "output.txt"



