######################################################################
# Automatically generated by qmake (1.07a) Thu Jun 9 14:53:55 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .
CONFIG -= qt

# Input
HEADERS += BoolArray.h GraphMeasure.h RankCorr.h
SOURCES += GraphCluster.cpp \
           GraphMeasure.cpp \
           RankCorr.cpp
